import { FormEvent, useEffect, useState } from "react";
import { invoke } from "@tauri-apps/api/core";

type Page="dashboard"|"organization"|"departments"|"positions"|"employees"|"users"|"settings";
type Session={token:string;username:string;display_name:string;permissions:string[]};
type Summary={employees:number;target_hc:number;fte:number;vacancies:number};
type AppIdentity={edition:"CENTRAL"|"UNIT";site_code?:string;site_name?:string};
type ProvisionInspection={package_id:string;source_site_code:string;target_site_code:string;target_site_name:string;issued_at:string;expires_at:string;key_id:string;key_env:string;user_count:number;usernames:string[];users:{username:string;role_code:string;permissions:string[];scopes:{scope_type:string;company_id?:string;department_id?:string}[]}[]};
type SigningKeyStatus={installed:boolean;key_id?:string;key_env?:string;embedded_trust:boolean};
const menu:{id:Page;label:string;permission:string}[]=[
 {id:"dashboard",label:"Dashboard",permission:"dashboard.view"},{id:"organization",label:"Organization Chart",permission:"department.view"},
 {id:"departments",label:"หน่วยงาน",permission:"department.view"},{id:"positions",label:"ตำแหน่ง",permission:"position.view"},
 {id:"employees",label:"ข้อมูลพนักงาน",permission:"employee.view"},{id:"users",label:"ผู้ใช้งานและสิทธิ์",permission:"user.manage"},{id:"settings",label:"ตั้งค่า",permission:"settings.manage"}
];

export function App(){
 const [setup,setSetup]=useState<boolean|null>(null),[identity,setIdentity]=useState<AppIdentity|null|undefined>(undefined),[buildEdition,setBuildEdition]=useState<"CENTRAL"|"UNIT"|null>(null),[session,setSession]=useState<Session|null>(null),[page,setPage]=useState<Page>("dashboard"),[error,setError]=useState("");
 useEffect(()=>{Promise.all([invoke<boolean>("needs_setup"),invoke<AppIdentity|null>("app_identity"),invoke<"CENTRAL"|"UNIT">("build_edition")]).then(([s,i,b])=>{setSetup(s);setIdentity(i);setBuildEdition(b)}).catch(e=>setError(String(e)))},[]);
 async function submit(e:FormEvent<HTMLFormElement>){
  e.preventDefault();setError("");const f=new FormData(e.currentTarget),username=String(f.get("username")||""),password=String(f.get("password")||"");
  try{
   if(setup){if(buildEdition!=="CENTRAL")throw new Error("Unit Edition ต้อง Provision จาก Central ก่อน");if(!identity){await invoke("initialize_central",{siteCode:String(f.get("siteCode")||"CENTRAL"),siteName:String(f.get("siteName")||"ส่วนกลาง")});setIdentity({edition:"CENTRAL",site_code:String(f.get("siteCode")||"CENTRAL"),site_name:String(f.get("siteName")||"ส่วนกลาง")})}await invoke("create_first_admin",{username,password,displayName:String(f.get("displayName")||"")});setSetup(false)}
   else setSession(await invoke<Session>("login",{username,password}));
  }catch(e){setError(String(e))}
 }
 if(setup===null||buildEdition===null)return <main className="login-shell"><section className="login-card"><h1>Roster Master Desktop</h1><p>กำลังเปิดฐานข้อมูลในเครื่อง…</p>{error&&<div className="error">{error}</div>}</section></main>;
 if(buildEdition==="UNIT"&&!identity)return <UnitProvision onDone={(i)=>{setIdentity(i);setSetup(false)}}/>;
 if(!session)return <main className="login-shell"><form className="login-card" onSubmit={submit}><div className="brand-mark">RM</div><h1>{setup?"ตั้งค่าระบบครั้งแรก":"Roster Master Desktop"}</h1><p>{setup?"สร้างบัญชี System Admin สำหรับเครื่องนี้":"ระบบบริหารอัตรากำลัง • Offline-first"}</p>{setup&&!identity&&<><label>รหัส Site<input name="siteCode" defaultValue="CENTRAL" required/></label><label>ชื่อ Site<input name="siteName" defaultValue="ส่วนกลาง" required/></label></>}{setup&&<label>ชื่อผู้ดูแลระบบ<input name="displayName" required/></label>}<label>ชื่อผู้ใช้<input name="username" required autoFocus/></label><label>รหัสผ่าน<input name="password" type="password" minLength={setup?10:1} required/></label>{error&&<div className="error">{error}</div>}<button>{setup?"สร้างผู้ดูแลระบบ":"เข้าสู่ระบบ"}</button><small>{setup?"รหัสผ่านอย่างน้อย 10 ตัวอักษร":"ตรวจสอบบัญชีจาก SQLite ในเครื่อง"}</small></form></main>;
 const allowed=menu.filter(m=>session.permissions.includes(m.permission));
 return <div className="app-shell"><aside><div className="app-brand"><b>Roster Master</b><span>Desktop v0.1 · {identity?.edition||buildEdition}</span></div><nav>{allowed.map(m=><button key={m.id} className={page===m.id?"active":""} onClick={()=>setPage(m.id)}>{m.label}</button>)}</nav><div className="user-box"><b>{session.display_name}</b><span>{session.username}</span><button onClick={async()=>{try{await invoke("logout",{token:session.token})}finally{setSession(null)}}}>ออกจากระบบ</button></div></aside><main className="content"><header><div><h1>{menu.find(x=>x.id===page)?.label}</h1><p>Desktop จาก Roster Master v5.55</p></div><div className="offline">● Local SQLite</div></header>{page==="dashboard"?<Dashboard session={session}/>:page==="departments"?<Departments session={session}/>:page==="positions"?<Positions session={session}/>:page==="employees"?<Employees session={session}/>:page==="users"?<UserAdmin session={session}/>:<Placeholder title={menu.find(x=>x.id===page)?.label||""}/>}</main></div>
}

function UnitProvision({onDone}:{onDone:(i:AppIdentity)=>void}){
 const [packageJson,setPackageJson]=useState(""),[inspection,setInspection]=useState<ProvisionInspection|null>(null),[site,setSite]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function choose(file?:File){if(!file)return;setError("");setInspection(null);const text=await file.text();setPackageJson(text);try{const x=await invoke<ProvisionInspection>("inspect_provision_package",{packageJson:text});setInspection(x);setSite("")}catch(e){setError(String(e))}}
 async function install(){if(!inspection||site!==inspection.target_site_code)return setError("กรุณาพิมพ์ Site Code ให้ตรงกับ Package");setBusy(true);setError("");try{await invoke("import_provision_package",{packageJson,expectedSiteCode:site});onDone({edition:"UNIT",site_code:inspection.target_site_code,site_name:inspection.target_site_name})}catch(e){setError(String(e))}finally{setBusy(false)}}
 return <main className="login-shell"><section className="login-card"><div className="brand-mark">RM</div><h1>Provision Roster Master Unit</h1><p>นำเข้า .rmpkg ที่ลงนามโดย Central และตรงกับ Trust Anchor ที่ฝังในโปรแกรม</p><label>เลือก Provision Package<input type="file" accept=".rmpkg,application/json" onChange={e=>choose(e.target.files?.[0])}/></label>{inspection&&<div className="provision-summary"><b>{inspection.target_site_name}</b><span>Site: {inspection.target_site_code}</span><span>ผู้ใช้: {inspection.user_count}</span><span>หมดอายุ: {new Date(inspection.expires_at).toLocaleString()}</span><span>Key: {inspection.key_id} ({inspection.key_env})</span>{inspection.users.map(u=><div className="provision-user" key={u.username}><b>{u.username} · {u.role_code}</b><small>Permissions: {u.permissions.join(", ")||"-"}</small><small>Scopes: {u.scopes.map(s=>`${s.scope_type}${s.company_id?`:${s.company_id}`:""}${s.department_id?`/${s.department_id}`:""}`).join(", ")||"-"}</small></div>)}</div>}{inspection&&<label>พิมพ์ Site Code เพื่อยืนยัน<input value={site} onChange={e=>setSite(e.target.value)} /></label>}{error&&<div className="error">{error}</div>}<button disabled={!inspection||busy} onClick={install}>{busy?"กำลังนำเข้า…":"ยืนยันและ Provision เครื่องนี้"}</button><small>Unit ไม่สามารถสร้าง System Admin หรือเปลี่ยน Site identity เองได้</small></section></main>
}

function Dashboard({session}:{session:Session}){
 const [s,setS]=useState<Summary|null>(null),[error,setError]=useState("");
 useEffect(()=>{invoke<Summary>("dashboard_summary",{token:session.token}).then(setS).catch(e=>setError(String(e)))},[]);
 return <>{error&&<div className="error">{error}</div>}<section className="cards"><Metric title="พนักงานทั้งหมด" value={s?String(s.employees):"…"} note="Active HC"/><Metric title="กรอบอัตรา" value={s?s.target_hc.toFixed(2):"…"} note="Target HC"/><Metric title="FTE ปัจจุบัน" value={s?s.fte.toFixed(2):"…"} note="Effective Assignment"/><Metric title="ตำแหน่งว่าง" value={s?s.vacancies.toFixed(2):"…"} note="Target - FTE"/></section><section className="panel"><h2>อัตรากำลังรายบริษัท</h2><p>โมดูลถัดไปจะอ่าน Company / Target HC / Actual HC / FTE จาก SQLite</p><div className="chart-placeholder">Company Workforce Chart</div></section><section className="panel"><h2>พนักงานใกล้ครบทดลองงาน 90 วัน</h2><p>คงกฎจาก v5.55 และจะคำนวณจากวันที่เริ่มงานใน SQLite</p></section></>
}
function Metric(p:{title:string;value:string;note:string}){return <article className="metric"><span>{p.title}</span><strong>{p.value}</strong><small>{p.note}</small></article>}
function Placeholder({title}:{title:string}){return <section className="panel"><h2>{title}</h2><p>โมดูลนี้กำลังย้ายจาก Roster Master v5.55</p></section>}

type Group={id:string;code:string;name:string}; type Company={id:string;code:string;name:string;company_group_id?:string}; type Unit={id:string;code:string;name:string;company_id:string;parent_id?:string;unit_type:string}; type Pos={id:string;code:string;name:string;org_unit_id:string;grade?:number;target_hc:number};

function Departments({session}:{session:Session}){
 const [groups,setGroups]=useState<Group[]>([]),[companies,setCompanies]=useState<Company[]>([]),[units,setUnits]=useState<Unit[]>([]),[error,setError]=useState("");
 const load=()=>Promise.all([invoke<Group[]>("list_company_groups",{token:session.token}),invoke<Company[]>("list_companies",{token:session.token}),invoke<Unit[]>("list_org_units",{token:session.token})]).then(([g,c,u])=>{setGroups(g);setCompanies(c);setUnits(u)}).catch(e=>setError(String(e)));
 useEffect(()=>{load()},[]);
 async function addGroup(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await invoke("add_company_group",{token:session.token,code:String(f.get("code")),name:String(f.get("name"))});e.currentTarget.reset();load()}catch(e){setError(String(e))}}
 async function addCompany(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await invoke("add_company",{token:session.token,code:String(f.get("code")),name:String(f.get("name")),companyGroupId:String(f.get("group")||"")||null});e.currentTarget.reset();load()}catch(e){setError(String(e))}}
 async function addUnit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await invoke("add_org_unit",{token:session.token,code:String(f.get("code")),name:String(f.get("name")),companyId:String(f.get("company")),parentId:String(f.get("parent")||"")||null,unitType:String(f.get("type"))});e.currentTarget.reset();load()}catch(e){setError(String(e))}}
 return <>{error&&<div className="error">{error}</div>}<section className="panel"><h2>โครงสร้างองค์กร</h2><p>กลุ่มบริษัท → บริษัท → ส่วน/แผนก/หน่วยงาน จาก SQLite</p><div className="org-grid">{companies.map(c=><article className="org-company" key={c.id}><b>{c.code} · {c.name}</b><small>{groups.find(g=>g.id===c.company_group_id)?.name||"ไม่ระบุกลุ่มบริษัท"}</small>{units.filter(u=>u.company_id===c.id).map(u=><div className="org-unit" key={u.id}>{u.code} · {u.name}<span>{u.unit_type}</span></div>)}</article>)}</div></section>{session.permissions.includes("department.manage")&&<section className="panel"><h2>เพิ่มโครงสร้าง</h2><div className="forms"><form onSubmit={addGroup}><h3>กลุ่มบริษัท</h3><input name="code" placeholder="รหัส" required/><input name="name" placeholder="ชื่อกลุ่มบริษัท" required/><button>เพิ่ม</button></form><form onSubmit={addCompany}><h3>บริษัท</h3><input name="code" placeholder="รหัส" required/><input name="name" placeholder="ชื่อบริษัท" required/><select name="group"><option value="">ไม่ระบุกลุ่ม</option>{groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select><button>เพิ่ม</button></form><form onSubmit={addUnit}><h3>หน่วยงาน</h3><input name="code" placeholder="รหัส" required/><input name="name" placeholder="ชื่อหน่วยงาน" required/><select name="company" required><option value="">เลือกบริษัท</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select name="parent"><option value="">ไม่มีหน่วยงานแม่</option>{units.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select><select name="type"><option value="SECTION">ส่วน</option><option value="DEPARTMENT">แผนก</option><option value="UNIT">หน่วยงาน</option></select><button>เพิ่ม</button></form></div></section>}</>
}
function Positions({session}:{session:Session}){
 const [positions,setPositions]=useState<Pos[]>([]),[units,setUnits]=useState<Unit[]>([]),[error,setError]=useState("");
 const load=()=>Promise.all([invoke<Pos[]>("list_positions",{token:session.token}),invoke<Unit[]>("list_org_units",{token:session.token})]).then(([p,u])=>{setPositions(p);setUnits(u)}).catch(e=>setError(String(e)));
 useEffect(()=>{load()},[]);
 async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await invoke("add_position",{token:session.token,code:String(f.get("code")),name:String(f.get("name")),orgUnitId:String(f.get("unit")),grade:f.get("grade")?Number(f.get("grade")):null,targetHc:Number(f.get("target"))});e.currentTarget.reset();load()}catch(e){setError(String(e))}}
 return <>{error&&<div className="error">{error}</div>}<section className="panel"><h2>ตำแหน่งและกรอบอัตรา</h2><div className="table-wrap"><table><thead><tr><th>รหัส</th><th>ตำแหน่ง</th><th>หน่วยงาน</th><th>Grade</th><th>กรอบ HC</th></tr></thead><tbody>{positions.map(p=><tr key={p.id}><td>{p.code}</td><td>{p.name}</td><td>{units.find(u=>u.id===p.org_unit_id)?.name||"-"}</td><td>{p.grade??"-"}</td><td>{p.target_hc}</td></tr>)}</tbody></table></div></section>{session.permissions.includes("position.manage")&&<section className="panel"><h2>เพิ่มตำแหน่ง</h2><form className="inline-form" onSubmit={add}><input name="code" placeholder="รหัสตำแหน่ง" required/><input name="name" placeholder="ชื่อตำแหน่ง" required/><select name="unit" required><option value="">เลือกหน่วยงาน</option>{units.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select><input name="grade" type="number" min="1" max="99" placeholder="Grade"/><input name="target" type="number" min="0" step="0.01" defaultValue="1" required/><button>เพิ่มตำแหน่ง</button></form></section>}</>
}

type Employee={id:string;employee_code:string;prefix?:string;full_name:string;nickname?:string;gender?:string;birth_date?:string;national_id?:string;nationality?:string;education?:string;home_company_id?:string;phone?:string;email?:string;hire_date?:string;probation_end_date?:string;status:string};
type Assignment={id:string;employee_id:string;position_id:string;role_type:string;fte?:number;effective_from?:string;effective_to?:string};

function Employees({session}:{session:Session}){
 const [employees,setEmployees]=useState<Employee[]>([]),[assignments,setAssignments]=useState<Assignment[]>([]),[companies,setCompanies]=useState<Company[]>([]),[positions,setPositions]=useState<Pos[]>([]),[error,setError]=useState("");
 const load=()=>Promise.all([invoke<Employee[]>("list_employees",{token:session.token}),invoke<Assignment[]>("list_assignments",{token:session.token}),invoke<Company[]>("list_companies",{token:session.token}),invoke<Pos[]>("list_positions",{token:session.token})]).then(([e,a,c,p])=>{setEmployees(e);setAssignments(a);setCompanies(c);setPositions(p)}).catch(e=>setError(String(e)));
 useEffect(()=>{load()},[]);
 async function addEmployee(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const val=(k:string)=>String(f.get(k)||"")||null;try{await invoke("add_employee",{token:session.token,input:{employee_code:val("employee_code"),prefix:val("prefix"),full_name:val("full_name"),nickname:val("nickname"),gender:val("gender"),birth_date:val("birth_date"),national_id:val("national_id"),nationality:val("nationality"),education:val("education"),home_company_id:val("home_company_id"),employment_type_id:null,phone:val("phone"),email:val("email"),address:val("address"),emergency_contact:val("emergency_contact"),emergency_phone:val("emergency_phone"),hire_date:val("hire_date"),probation_end_date:null,termination_date:null,termination_reason:null,status:"ACTIVE"}});e.currentTarget.reset();load()}catch(e){setError(String(e))}}
 async function addAssignment(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await invoke("add_assignment",{token:session.token,employeeId:String(f.get("employee")),positionId:String(f.get("position")),roleType:String(f.get("role")),fte:f.get("fte")?Number(f.get("fte")):null,effectiveFrom:String(f.get("from")||"")||null,effectiveTo:String(f.get("to")||"")||null});e.currentTarget.reset();load()}catch(e){setError(String(e))}}
 return <>{error&&<div className="error">{error}</div>}<section className="panel"><h2>Employee Master</h2><p>ข้อมูลพนักงานจาก SQLite • {employees.length} รายการ</p><div className="table-wrap"><table><thead><tr><th>รหัส</th><th>ชื่อ-นามสกุล</th><th>บริษัทต้นสังกัด</th><th>ตำแหน่งหลัก</th><th>FTE</th><th>เริ่มงาน</th><th>ครบทดลองงาน</th><th>สถานะ</th></tr></thead><tbody>{employees.map(e=>{const aa=assignments.filter(a=>a.employee_id===e.id),primary=aa.find(a=>a.role_type==="PRIMARY"),fte=aa.reduce((s,a)=>s+(a.fte??(aa.length?1/aa.length:0)),0);return <tr key={e.id}><td>{e.employee_code}</td><td>{e.prefix||""} {e.full_name}</td><td>{companies.find(c=>c.id===e.home_company_id)?.name||"-"}</td><td>{positions.find(p=>p.id===primary?.position_id)?.name||"-"}</td><td>{fte.toFixed(2)}</td><td>{e.hire_date||"-"}</td><td>{e.probation_end_date||"-"}</td><td>{e.status}</td></tr>})}</tbody></table></div></section>
 {session.permissions.includes("employee.create")&&<section className="panel"><h2>เพิ่มพนักงาน</h2><form className="employee-form" onSubmit={addEmployee}><input name="employee_code" placeholder="รหัสพนักงาน" required/><select name="prefix"><option value="">คำนำหน้า</option><option>นาย</option><option>นาง</option><option>นางสาว</option></select><input name="full_name" placeholder="ชื่อ-นามสกุล" required/><input name="nickname" placeholder="ชื่อเล่น"/><select name="gender"><option value="">เพศ</option><option>ชาย</option><option>หญิง</option><option>อื่นๆ</option></select><input name="birth_date" type="date" title="วันเกิด"/><input name="national_id" placeholder="เลขบัตรประชาชน"/><input name="nationality" placeholder="สัญชาติ"/><input name="education" placeholder="วุฒิการศึกษา"/><select name="home_company_id"><option value="">บริษัทต้นสังกัด</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input name="phone" placeholder="โทรศัพท์"/><input name="email" type="email" placeholder="อีเมล"/><input name="address" placeholder="ที่อยู่"/><input name="emergency_contact" placeholder="ผู้ติดต่อฉุกเฉิน"/><input name="emergency_phone" placeholder="เบอร์ติดต่อฉุกเฉิน"/><label>วันที่เริ่มงาน<input name="hire_date" type="date"/></label><button>บันทึกพนักงาน</button></form></section>}
 {session.permissions.includes("assignment.manage")&&<section className="panel"><h2>เพิ่ม Assignment</h2><form className="assignment-form" onSubmit={addAssignment}><select name="employee" required><option value="">เลือกพนักงาน</option>{employees.map(e=><option key={e.id} value={e.id}>{e.employee_code} · {e.full_name}</option>)}</select><select name="position" required><option value="">เลือกตำแหน่ง</option>{positions.map(p=><option key={p.id} value={p.id}>{p.code} · {p.name}</option>)}</select><select name="role"><option value="PRIMARY">ตำแหน่งหลัก</option><option value="SECONDARY">ตำแหน่งรอง</option><option value="COORDINATION">ประสานงาน</option></select><input name="fte" type="number" min="0.01" max="1" step="0.01" placeholder="FTE (เว้นว่าง=แบ่งอัตโนมัติ)"/><input name="from" type="date" title="วันที่มีผล"/><input name="to" type="date" title="วันที่สิ้นสุด"/><button>เพิ่ม Assignment</button></form></section>}</>
}

type ManagedUser={id:string;username:string;display_name:string;is_active:boolean;role_code:string;scope_type:string;company_id?:string;department_id?:string};
function UserAdmin({session}:{session:Session}){
 const [users,setUsers]=useState<ManagedUser[]>([]),[companies,setCompanies]=useState<Company[]>([]),[units,setUnits]=useState<Unit[]>([]),[error,setError]=useState("");
 const [selected,setSelected]=useState<string[]>([]),[keyStatus,setKeyStatus]=useState<SigningKeyStatus|null>(null),[notice,setNotice]=useState("");
 const load=()=>Promise.all([invoke<ManagedUser[]>("list_managed_users",{token:session.token}),invoke<Company[]>("list_companies",{token:session.token}),invoke<Unit[]>("list_org_units",{token:session.token})]).then(([u,c,d])=>{setUsers(u);setCompanies(c);setUnits(d)}).catch(e=>setError(String(e)));
 const loadKey=()=>invoke<SigningKeyStatus>("signing_key_status",{token:session.token}).then(setKeyStatus).catch(()=>setKeyStatus(null));
 useEffect(()=>{load();loadKey()},[]);
 async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),scope=String(f.get("scope"));try{await invoke("create_managed_user",{token:session.token,input:{username:String(f.get("username")),password:String(f.get("password")),display_name:String(f.get("displayName")),role_code:String(f.get("role")),scope_type:scope,company_id:scope==="COMPANY"?String(f.get("company")||"")||null:null,department_id:scope==="DEPARTMENT"?String(f.get("department")||"")||null:null}});e.currentTarget.reset();load()}catch(e){setError(String(e))}}
 async function installKey(file?:File){if(!file)return;setError("");setNotice("");try{await invoke("install_signing_key",{token:session.token,keyJson:await file.text()});setNotice("ติดตั้ง ALPHA Signing Key สำเร็จ");loadKey()}catch(e){setError(String(e))}}
 async function exportPkg(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");setNotice("");const f=new FormData(e.currentTarget);try{const json=await invoke<string>("export_provision_package",{token:session.token,targetSiteCode:String(f.get("siteCode")),targetSiteName:String(f.get("siteName")),userIds:selected,validDays:Number(f.get("validDays")||7)});const blob=new Blob([json],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`roster-${String(f.get("siteCode")).trim()}-${Date.now()}.rmpkg`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice("สร้าง Provision Package สำเร็จ")}catch(e){setError(String(e))}}
 return <>{error&&<div className="error">{error}</div>}{notice&&<div className="success">{notice}</div>}
 <section className="panel"><h2>ผู้ใช้งานและสิทธิ์</h2><p>จัดการจาก Central เท่านั้น • รหัสผ่านจัดเก็บเป็น Hash</p><div className="table-wrap"><table><thead><tr><th>เลือกส่ง Unit</th><th>Username</th><th>ชื่อ</th><th>Role</th><th>Scope</th><th>สถานะ</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><input type="checkbox" disabled={u.role_code==="SYSTEM_ADMIN"} checked={selected.includes(u.id)} onChange={e=>setSelected(e.target.checked?[...selected,u.id]:selected.filter(x=>x!==u.id))}/></td><td>{u.username}</td><td>{u.display_name}</td><td>{u.role_code}</td><td>{u.scope_type}</td><td>{u.is_active?"ใช้งาน":"ปิด"}</td></tr>)}</tbody></table></div></section>
 <section className="panel"><h2>สร้างผู้ใช้สำหรับหน่วยงาน</h2><form className="employee-form" onSubmit={add}><input name="username" placeholder="Username" required/><input name="displayName" placeholder="ชื่อผู้ใช้" required/><input name="password" type="password" minLength={10} placeholder="รหัสผ่านอย่างน้อย 10 ตัว" required/><select name="role"><option value="COMPANY_HR">HR บริษัท</option><option value="MANAGER">Manager</option><option value="STAFF">Staff</option><option value="VIEWER">Viewer</option><option value="CENTRAL_HR">Central HR</option></select><select name="scope"><option value="COMPANY">เฉพาะบริษัท</option><option value="DEPARTMENT">เฉพาะหน่วยงาน</option><option value="GLOBAL">ทุกบริษัท</option></select><select name="company"><option value="">เลือกบริษัท</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select name="department"><option value="">เลือกหน่วยงาน</option>{units.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select><button>สร้างผู้ใช้</button></form></section>
 <section className="panel"><h2>ALPHA Signing Key</h2><p>{keyStatus?.installed?`ติดตั้งแล้ว: ${keyStatus.key_id} · ${keyStatus.key_env} · Trust ${keyStatus.embedded_trust?"OK":"ไม่ตรง"}`:"ยังไม่ได้ติดตั้ง Signing Key"}</p><input type="file" accept=".rmkey,application/json" onChange={e=>installKey(e.target.files?.[0])}/><small>ไฟล์ private .rmkey ใช้เฉพาะ Central Alpha และห้ามเก็บใน repository</small></section>
 <section className="panel"><h2>Export Provision Package (.rmpkg)</h2><form className="inline-form" onSubmit={exportPkg}><input name="siteCode" placeholder="Site Code เช่น PKT-S01" required/><input name="siteName" placeholder="ชื่อ Site" required/><input name="validDays" type="number" min="1" max="30" defaultValue="7" required/><button disabled={!keyStatus?.installed||selected.length===0}>สร้าง .rmpkg ({selected.length} ผู้ใช้)</button></form><p>Package ไม่มี plaintext password และ Unit จะรับเฉพาะ Package ที่ตรวจ signature/target site/expiry ผ่านเท่านั้น</p></section>
 </>;
}

